### ISSUE TITLE
Install and setup Choreo, run tests to compare it to Pathplanner

### ISSUE THREAD

**Issue by andvari101** [Mercs-MSA/2024_V2#5]

**Comment by danmargavio** [comment]
Can I get a report on the outcome of this activity? Do we need to train students/mentors on this?

**Comment by Shlok-Mehta128** [comment]
Brady and I went through and set up Choreo and ran different tests with it, and we realized that Pathplanner would be much more efficient and a better option since we had a year of experience with Pathplanner and we were still new to Choreo. Also, Pathplanner 2025 has most of the same features as Choreo, so it is not worth switching to it.
